### PR TITLE
Make noarch

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
hmm, lets see if noarch_platforms even lints correctly:
https://github.com/conda-forge/conda-smithy-feedstock/pull/311

**Comment by beckermr** [comment]
Is it the linux64 selector?

**Comment by hmaarrfk** [comment]
I don't get it there is no error with the conda-smithy feedstock...

**Comment by hmaarrfk** [comment]
oh that would be it...

**Comment by hmaarrfk** [comment]
oh well it was worth a shot.

**Pull request closed without merging**
