### PR TITLE
Update to 3.3.0

### PR DESCRIPTION
**Pull request by ccordoba12**
Pinging @jjhelmus, @mingwandroid and @nehaljwani about this one.

Please notice that this release adds two new dependencies: `keyring` and `spyder-kernels`. For now please only package `spyder-kernels` versions strictly less than **1.0** (the current one is **0.2.4**), which are going to remain compatible with our Spyder 3 series.

We also have `spyder-kernels` versions greater than 1.0 (the current one is **1.0.1**) but those are for our master branch, so they don't need to be part of Anaconda for now.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Please look at the `0.x` branch there for the 0.2.4 recipe.

**Comment by jjhelmus** [comment]
@ccordoba12 Thanks for the heads up on the new release and additional dependencies.  The team is quite booked this week with the Python 3.7 release and SciPy but I'll but this on my to-do list for the following week.

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it @jjhelmus!

**Comment by mingwandroid** [comment]
I'm looking into this now as part of the 3.7.0 rollout.

**Comment by ccordoba12** [comment]
Thanks Ray!

**Pull request merged**
