### PR TITLE
Change main channel from main to beta

### PR DESCRIPTION
**Pull request by ccordoba12**
@conda-forge/core, I want to upload our beta packages to the beta conda-forge channel. Is this the right way to do it?

### CODE REVIEW

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@conda-forge/core, could you help me by removing these packages?

https://anaconda.org/conda-forge/spyder/4.0.0b1/download/win-64/spyder-4.0.0b1-py36_2.tar.bz2
https://anaconda.org/conda-forge/spyder/4.0.0b1/download/win-64/spyder-4.0.0b1-py27_2.tar.bz2

We don't want to distribute our betas as in the main conda-forge channel (that was my mistake, but I'm unable to remove those packages).

**Comment by isuruf** [comment]
Removed broken ones. Correct way is to create a recipe/conda_build_config.yaml and add,
```yaml
channel_targets:
- conda-forge beta
```
and then rerender.

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
Thanks a lot @isuruf!

**Pull request merged**
