### PR TITLE
PR: Update to version 6.0.0b3

### PR DESCRIPTION
**Pull request by dalthviz**
Dependencies changes:

- `paramiko` (removed)

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dalthviz** [comment]
@conda-forge-admin, please rerender

**Comment by dalthviz** [comment]
Note: CI checks not running probably due to GitHub Actions degraded status - https://www.githubstatus.com/incidents/m70hk23gx3nx - Need to wait before merging this

**Review by jakirkham — CHANGES_REQUESTED** [review]
CI did not run. Do not merge until that is resolved

xref: https://github.com/conda-forge/status/issues/184

**Comment by dalthviz** [comment]
Thank you @jakirkham for keeping an eye on this! Just to be sure, it should be okay to merge this now, right?

**Comment by jakirkham** [comment]
Am seeing green Azure CI. So yeah let's try

We can keep an eye on the `dev` branch and follow up if needed

**Pull request merged**
