### PR TITLE
PR: Enable aarch64 build

### PR DESCRIPTION
**Pull request by steff456**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by steff456** [comment]
@conda-forge-admin, please rerender

**Review by ccordoba12 — COMMENTED** [review]
Thanks @steff456 for this! Please skip the build when `aarch64 and py36` because there are not rtree packages available for that combo.

Then this should be ready.

**Comment by steff456** [comment]
@conda-forge-admin, please rerender

**Review by ccordoba12 — APPROVED** [review]
I never thought to see Spyder working in aarch64, this is really cool! Thanks a lot @steff456!

**Pull request merged**
