### PR TITLE
Update to v4.0rc3

### PR DESCRIPTION
**Pull request by ccordoba12**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by ccordoba12** [comment]
> I tried to re-render for you but ran into some issues, please ping conda-forge/core for further assistance. You can also try re-rendering locally.

@conda-forge/core, I think this message is more confusing than the one before because "some issues" is very vague.

I guess there was nothing to do here, and so the bot could not rerender the feedstock, right?

**Comment by isuruf** [comment]
Nope. That means the bot had issues. If you find the messages confusing, please send a PR to https://github.com/conda-forge/conda-forge-webservices/blob/master/conda_forge_webservices/commands.py

**Comment by ccordoba12** [comment]
> Nope. That means the bot had issues

But what issues?

**Comment by isuruf** [comment]
conda-forge-pinning was out-of-date. I restarted the webservice to fix that. Error messages are not shown to avoid exposing tokens.

**Comment by ccordoba12** [comment]
Ok, thanks @isuruf for taking the time to explain me that!

**Pull request merged**
