### PR TITLE
Fix provider

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Ref #124
Ref https://conda-forge.org/status/#python310

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
Note, this currently fails because of https://github.com/conda-forge/status/issues/125

**Comment by ccordoba12** [comment]
Thanks a lot for your help with this @BastianZim! Let us know when the problem with Azure is fixed, so we can merge this one.

**Comment by BastianZim** [comment]
Seems to be working :tada:

**Comment by ccordoba12** [comment]
No problrm. Thanks again @BastianZim!

**Comment by BastianZim** [comment]
Thanks for merging!

**Pull request merged**
