### PR TITLE
PR: Update psutil

### PR DESCRIPTION
**Pull request by goanpeca**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by goanpeca** [comment]
@ccordoba12 ready!

**Comment by ccordoba12** [comment]
Pinging @jjhelmus about this one. This is a new build to fix a critical issue with our Kite integration with older psutil versions.

**Comment by jjhelmus** [comment]
I can make modification to `defaults` to add this change but I need some additional information on how this is expect to work.

The older builds of spyder are still available on conda-forge and will be installed without this new dependency information (and the parso constraint in #73) if those produce a more optimal solution.  Should these older builds be removed or hotfixed with the new dependency information?

Do these new dependency constrains apply to older versions of spyder?

**Comment by goanpeca** [comment]
>The older builds of spyder are still available on conda-forge and will be installed without this new dependency information (and the parso constraint in #73) if those produce a more optimal solution. Should these older builds be removed or hotfixed with the new dependency information?

The older builds can lead to envs where the versions are not ok but could be easily updated by the user (like the psutil case)

>Do these new dependency constrains apply to older versions of spyder?

We should have applied this to all the 4.x versions of Spyder out there, so it is probably our bad for not doing it on time.

>shoudl they be removed?

Not sure, what do you recommend?

**Comment by jjhelmus** [comment]
> Not sure, what do you recommend?

For `defaults` we do not remove packages except in extreme cases so I was planning on hotfixing the existing packages to add the parso requirement and place minimum version of the psutil requirement.

`conda-forge` has a tradition of moving packages with incorrect dependency information to the `broken` label so that users do install them but they are still available for historic archival reasons.  This could be done here.  Alternatively, the dependency information in conda-forge can be hotfixed although the process is a bit more involved.

**Comment by ccordoba12** [comment]
> For defaults we do not remove packages except in extreme cases so I was planning on hotfixing the existing packages to add the parso requirement and place minimum version of the psutil requirement

I agree this is the best solution for defaults, i.e. both 4.0.0 and 4.0.1 should have parso `0.5.2` and psutil `>=5.3` among their dependencies.

> This could be done here

We don't have permissions to change labels in the conda-forge channel. But I think you do, so if you could help us with that, we'd really appreciate it (I think moving 4.0.1 builds 0 and 1 to `broken` should be enough).

**Comment by goanpeca** [comment]
>For defaults we do not remove packages except in extreme cases so I was planning on hotfixing the existing packages to add the parso requirement and place minimum version of the psutil requirement.

Ok, then hotfix is the way. Thanks a lot!

>conda-forge has a tradition of moving packages with incorrect dependency information to the broken label so that users do install them but they are still available for historic archival reasons. This could be done here. Alternatively, the dependency information in conda-forge can be hotfixed although the process is a bit more involved.

Yes I have seen, will ask the previoues versions to be removed then.

@ccordoba12 agree with this?

**Comment by ccordoba12** [comment]
> do you agree with this?

Yes. I think it's better to avoid conda picking up wrong versions when solving dependencies.

**Comment by jjhelmus** [comment]
I've created conda-forge/cf-mark-broken#8 which will move the build 0 and 1 packages in conda-forge to the `broken` label once merged.

I also hotfixed the dependency information for the spyder 4.0.0 and 4.0.1 packages in defaults in AnacondaRecipes/repodata-hotfixes#69.  These changes are live in defaults.

Sorry for being a bit delayed in responding to this issue. The distribution team is preparing releases of Miniconda and Anaconda and I am the release manager for both.  This role has been taking a lot of my time the last few days.

**Comment by goanpeca** [comment]
>Sorry for being a bit delayed in responding to this issue. The distribution team is preparing releases of Miniconda and Anaconda and I am the release manager for both. This role has been taking a lot of my time the last few days.

No worries, we know how this goes :-) 

Thanks so much for your help @jjhelmus !

**Comment by ccordoba12** [comment]
> Sorry for being a bit delayed in responding to this issue. The distribution team is preparing releases of Miniconda and Anaconda and I am the release manager for both

When the new Anaconda release is planned for? We have an important release in the making with lots of bugfixes, and it's almost ready, so we'd really like for Anaconda to include it in its next version.

**Comment by jjhelmus** [comment]
> When the new Anaconda release is planned for?

The first RC went to QA yesterday with a goal of releasing sometime next week (might slip to the following week).

**Pull request merged**
