### PR TITLE
Move Windows reset Spyder settings shortcut to a separate json file

### PR DESCRIPTION
**Pull request by mrclary**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Address conda/menuinst#274
Fixes spyder-ide/spyder#23062

### CODE REVIEW

**Comment by mrclary** [comment]
@conda-forge-admin, please rerender

**Comment by mrclary** [comment]
@ccordoba12 this is ready for review. I tested the Azure artifact on macOS and Windows VM.

**Comment by mrclary** [comment]
...and the REQUIRED.app is no longer created.

**Review by ccordoba12 — APPROVED** [review]
Looks good to me, thanks @mrclary!

**Pull request merged**
