### PR TITLE
Ensure `packaging` is included for host

### PR DESCRIPTION
**Pull request by mrclary**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Using `packaging.parse` in `spyder.__init__` for version normalization requires including `packaging` in `host` in order to build the `spyder` conda package.

See spyder-ide/spyder#21836

### CODE REVIEW

**Comment by ccordoba12** [comment]
@mrclary, this is ready to be merged, right?

**Comment by mrclary** [comment]
@ccordoba12, yes it is ready. Does it need to be re-rendered first? Maybe that's why the Docker build is failing in Azure?

**Comment by ccordoba12** [comment]
There seems to be a problem with some of the packages used for cross compilation on Linux aarch64.

This is the error:

```python
conda.CondaMultiError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/conda-forge/noarch/sysroot_linux-aarch64-2.17-h5b4a56d_14.conda'.
  download saved to: /home/conda/feedstock_root/build_artifacts/pkg_cache/sysroot_linux-aarch64-2.17-h5b4a56d_14.conda
  expected sha256: 96e98e80535f177536a9c62886709288afef57ca146d696a4beab6a8c08442b1
  actual sha256: d239232cff55b45a1fbdea9fc660492afca16ba950785d9da3504f16de8fe765

Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/conda-forge/noarch/sysroot_linux-aarch64-2.17-h5b4a56d_14.conda'.
  download saved to: /home/conda/feedstock_root/build_artifacts/pkg_cache/sysroot_linux-aarch64-2.17-h5b4a56d_14.conda
  expected sha256: 96e98e80535f177536a9c62886709288afef57ca146d696a4beab6a8c08442b1
  actual sha256: d239232cff55b45a1fbdea9fc660492afca16ba950785d9da3504f16de8fe765

Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/conda-forge/noarch/sysroot_linux-64-2.12-he073ed8_17.conda'.
  download saved to: /home/conda/feedstock_root/build_artifacts/pkg_cache/sysroot_linux-64-2.12-he073ed8_17.conda
  expected sha256: e7c68a439924282f3659cfce326c89ce401b09037d561b3c2943d34b0dcb9b3e
  actual sha256: b4e4d685e41cb36cfb16f0cb15d2c61f8f94f56fab38987a44eff95d8a673fb5

Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/conda-forge/noarch/libgcc-devel_linux-64-13.2.0-ha9c7c90_105.conda'.
  download saved to: /home/conda/feedstock_root/build_artifacts/pkg_cache/libgcc-devel_linux-64-13.2.0-ha9c7c90_105.conda
  expected sha256: 9adf6a245905be5157ca41e7e2eb259c88535148d1c4cfb487a00a8e17ece127
  actual sha256: 858029ad4d66869c533bb5a22e95e7c044ca66c61d6f403f10d9ae074a0e360e
```

@conda-forge/core, do you know what's happening here?

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@mrclary, you were right: it was necessary a rerender to fix that error.

Now, please apply the changes in PR #168 to fix the linter error and do a rerender again (just in case, although I don't think it's necessary).

**Comment by mrclary** [comment]
@conda-forge-admin, please rerender

**Review by ccordoba12 — APPROVED** [review]
Thanks @mrclary!

**Pull request merged**
