### PR TITLE
Fix typo in menuinst v1 json file

### PR DESCRIPTION
**Pull request by mrclary**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes spyder-ide/spyder#22790

### CODE REVIEW

**Comment by mrclary** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
@mrclary, did you manually check that this fixes the problem for old `menuinst` versions?

**Comment by dalthviz** [comment]
Just in case, I think there is a config (`store_build_artifacts`) that can be set to enable downloading the package as an Azure pipeline artifact (https://conda-forge.org/docs/maintainer/conda_forge_yml/#azure). Maybe it could be worthy to enable that to check changes to the feedstock on PRs?

**Comment by mrclary** [comment]
> @mrclary, did you manually check that this fixes the problem for old `menuinst` versions?

Not yet.

> Just in case, I think there is a config (`store_build_artifacts`) that can be set to enable downloading the package as an Azure pipeline artifact (https://conda-forge.org/docs/maintainer/conda_forge_yml/#azure). Maybe it could be worthy to enable that to check changes to the feedstock on PRs?

That would be very useful. Do we need to make that change in a separate PR and merge that in first, or can that be included in the current PR?

**Comment by dalthviz** [comment]
> That would be very useful. Do we need to make that change in a separate PR and merge that in first, or can that be included in the current PR?

I think doing the change here should trigger the upload here but if that doesn't work we can try opening a PR only for that and then updating this one after that gets merged :+1:

**Comment by mrclary** [comment]
> I think doing the change here should trigger the upload here but if that doesn't work we can try opening a PR only for that and then updating this one after that gets merged 👍

I'll give a try.

**Comment by mrclary** [comment]
@dalthviz @ccordoba12 I don't see any artifacts on Azure. Did I do something wrong?

**Comment by ccordoba12** [comment]
@conda-forge-admin, please rerender

**Comment by ccordoba12** [comment]
Maybe a rerender is necessary?

**Comment by mrclary** [comment]
> Maybe a rerender is necessary?

That seemed to work. I can download artifacts!

**Comment by mrclary** [comment]
@conda-forge-admin, please rerender

**Comment by mrclary** [comment]
> @mrclary, did you manually check that this fixes the problem for old `menuinst` versions?

I've now tested on my Windows VM. With `menuinst=1.4.20` and the build artifact, Spyder installs without error and the shortcuts are created.

**Review by dalthviz — APPROVED** [review]
Thanks @mrclary ! Checked installing locally the build from this PR on Windows and I was unable to see any traceback from menuinst (1.4.19) :+1:

**Pull request merged**
