### PR TITLE
Remove pins for pyqt and rope

### PR DESCRIPTION
**Pull request by ocefpaf**
@ccordoba12 I am slowly moving things to `qt/pyqt 5` can you take a look please?

### CODE REVIEW

**Comment by ccordoba12** [comment]
Nice!! Thanks a lot for this ;-)

Will merge as soon as it's green.

**Comment by ocefpaf** [comment]
All green @ccordoba12!

**Comment by ccordoba12** [comment]
Wouldn't it be better to remove the pin, as @jakirkham suggested?

**Comment by ocefpaf** [comment]
Pinning is better for future proofing the package and to ensure the right `qt` `pyqt` `4/5` will be properly installed. If you don't want that you can close this and remove the pin.

**Comment by ccordoba12** [comment]
The thing is we don't use this pin on Continuum to give the opportunity to people to use Spyder with Qt4 or Qt5.

But I'd like to talk to @jakirkham about it here.

**Comment by ocefpaf** [comment]
> The thing is we don't use this pin on Continuum to give the opportunity to people to use Spyder with Qt4 or Qt5.

What I am afraid is that you can get a `pyqt` compiled against `qt 4` in a `qt 5` installation or vice-n-versa. We could inspect the previous packages to ensure there is no unpinned `pyqt` build but that is what I wanted to avoid.

**Comment by ccordoba12** [comment]
Isn't it enough to have `pyqt` to the right version of `qt`?

**Comment by ocefpaf** [comment]
like I said, the problem is the unpinned pyqt out in the wild ;-)

I don't want to hunt them down and remove tthem. but feel free to close
this and unpin it.

On Mar 24, 2017 8:10 PM, "Carlos Cordoba" <notifications@github.com> wrote:

Isn't it enough to have pyqt to the right version of qt?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/spyder-feedstock/pull/12#issuecomment-289164262>,
or mute the thread

**Comment by ocefpaf** [comment]
Note that if users specify qt 4 together with spyder when installing they
will get the previous build number in a 'safe' way.

On Mar 24, 2017 8:23 PM, "Filipe Pires Alvarenga Fernandes" <
ocefpaf@gmail.com> wrote:

like I said, the problem is the unpinned pyqt out in the wild ;-)

I don't want to hunt them down and remove tthem. but feel free to close
this and unpin it.

On Mar 24, 2017 8:10 PM, "Carlos Cordoba" <notifications@github.com> wrote:

Isn't it enough to have pyqt to the right version of qt?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/spyder-feedstock/pull/12#issuecomment-289164262>,
or mute the thread

**Comment by ccordoba12** [comment]
@jakirkham, do you agree?

**Comment by ccordoba12** [comment]
Appveyor is reported as waiting although it's really green, so merging.

**Comment by jakirkham** [comment]
> do you agree?

My gut feeling is we shouldn't need to pin this unless a package actually doesn't support PyQt 5 for instance. That said, I know we did have some issues with underlying dependencies of Qt having incompatibilities between conda-forge and defaults. It's my understanding these have been resolved. So dropping the pinnings should be ok.

**Pull request merged**
